database:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: test
    database: toastr
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''

proxy-name: changeme

antibot:
  ratelimit: 12

version:
  min: 4
  max: 47

lobby:
  load-balancer: LOWEST
  send-on-close: true
  servers:
    - name: lobby
      restricted: false

auth:
  allowed_commands:
    - login
    - register

messages:
  motd:
    line1: '&6Another server running Toastr'
    line2: '&7Check us out on GitHub'

  tab:
    header: '&3Sergi Services &8┃ &rCurrently connected to &b&l<proxy> &rProxy'
    footer: >-
      There are &l&3<online> &ronline users on the Network &8┃ &rConnected to &b&l<server>

  alert: '&8[&4Alert&8] &r'
  server_id: '&2You are connected to <proxy>'

  staff:
    join: "&8[&2+&8] &3<player> &rjoined the network on &b<server> &7(<proxy>)"
    quit: "&8[&4-&8] &3<player> &rquit the network from &b<server> &7(<proxy>)"
    switch: "&8[&d*&8] &3<player> &rswitched from &b<from> &rto  &3<to> &7(<proxy>)"

  glist:
    global: 'There are &b<online> online players &fon the network'
    proxy: 'There are &b<online> online players &fon the <proxy> proxy.'
    per_server: '&e&l * &3<server>&r: &7(<online>)&r <players>'

  profile:
    usage: '&cUsage: /tprofile <username/uuid>'
    player_not_found: '&cPlayer not found'
    player_info:
      - '&7&m-------------------------'
      - '&3UUID&r: <uuid>'
      - '&3Username&r: <username>'
      - '&3Last Online&r: <last_online>'
      - '&3Proxy&r: <proxy>'
      - '&3Server&r: <server>'
      - '&3Account Type&r: <account_type>'
      - '&3First IP&r: <first_ip>'
      - '&3Last IP&r: <last_ip>'
      - '&3First Login&r: <first_login>'
      - '&3Last Login&r: <last_login>'
      - '&7&m-------------------------'
